services:
  mongodb:
    image: mongodb/mongodb-community-server
    container_name: mongodb
    ports:
      - "27017:27017"

  fastapi:
    build: .
    container_name: sgr
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

