Database:
  HOST: localhost
  PORT: 27017
  MAX_POOL_SIZE: 50

Auth:
  SECRET_KEY: hw4jf6uz8o4na1rc3pf9yxr8fn3gft3m
  USER_ACCESS_TOKEN_EXPIRE_MINUTES: 2160
  BOT_ACCESS_TOKEN_EXPIRE_MINUTES: 525600

Default:
  DEFAULT_AVATAR: "data:image/png;base64,/9j/4AAQSkZJRgABAQEAkACQAAD/2wBDAAIBAQIBAQICAgICAgICAwUDAwMDAwYEBAMFBwYHBwcGBwcICQsJCAgKCAcHCg0KCgsMDAwMBwkODw0MDgsMDAz/2wBDAQICAgMDAwYDAwYMCAcIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/wAARCAAwADADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDzeiiiugzCiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooA//2Q=="

Limits:
  GROUP_NAME_LENGTH_RANGE:
    MIN: 1
    MAX: 16
  GROUP_QA_LENGTH_RANGE:
    MIN: 0
    MAX: 16
  GROUP_AUDIO_LENGTH_RANGE:
    MIN: 1
    MAX: 60
  GROUP_AVATAR_SIZE_RANGE:
    MIN: 0
    MAX: 1024
  GROUP_FILE_SIZE_RANGE:
    MIN: 0
    MAX: 102400
  GROUP_REQUEST_EXPIRE_MINUTES: 10080
  GROUP_INVITE_EXPIRE_MINUTES: 10080
