Database:
  HOST: localhost
  PORT: 27017
  MAX_POOL_SIZE: 100

Auth:
  SECRET_KEY: hw4jf6uz8o4na1rc3pf9yxr8fn3gft3m  # JWT密钥
  SALT: jSJ1oGX6siEa50Nmq6xlYvD0IfnUlKrj        # 密码加盐
  USER_ACCESS_TOKEN_EXPIRE_MINUTES: 4320        # 用户Token过期时间 默认4320 单位: 分钟
  BOT_ACCESS_TOKEN_EXPIRE_MINUTES: 2628000      # 机器人Token过期时间 默认2628000 单位: 分钟

Default:
  # 用户/群的默认头像 base64格式
  DEFAULT_AVATAR: data:image/webp;base64,UklGRoIGAABXRUJQVlA4WAoAAAAQAAAASgAASgAAQUxQSEYEAAABoD79n+K2ndiu5Lga2UHTzM1YVVC58UvNpdL9wFRmZmZmZmZmZuY2zHldZsYw2AUzyVc4a3+7jogJUHYTlVVT673GTKbRq59aVZlQ41WnarJN+QIQMTMTQSHflK1J6XGQavADZGYqm5kx8BtSbulJMwNiEmYKZk7SzujJuSIzWWQuzp2s3UjPKjJZ5+LsKgeSXsDkJAde0lbaRyZHGf20nWl5Joc5X2NBewUmp7ngaalEBsh5yCRkElkkYYwVIswmJHQGSRRC2mnvAw7YeycKQYQwowU8IMmw5ajb53/666ZNv346//ajWkIJAs9sWoEEoe38ZR2j0ZijHcvObwMBKkwzSedZAI5e3BsZ9i4+GgQ4ny4v6TMZI1+9NhJcezWjEbGfLMtDMsbme7sj0e57m9GI0CsnHbAZ3dUXCffdReYcpMfSs5iM4cI/I/E/LwQj4ll6jMlFMsYDvo0sfnsAGlFxcpzOsRk9F1l9jsw5p2MmFckYjtxsZ/ORYETFSTEzWeCJyPITAjzzf6nADHf90taXu6JZkFJKNZA5nNRlq+skMCJqUEr7bBbeMmpr9JbQjH2tUgGZw/OR9efBjIKUqkEBmm9vPglijcqyAC+1t5QFOKuaRBbZWyTSlMhL4Gv2XkOJfGWBBMP77N0XClChCkTOHbA1cK4ITCVJ3O83W7/thxJUL0L8rq13mUQ9FgnP6bXTe04owo0y1L7Kzqp2kskIwamdNjpPBaeIHi7JlR4mYW4kYdx5gdyCnVGIPCnCPZdKLd0TSboepAj2eGtQYvCtPYCkYWpBjLDt1rVma29tQxIvVOVZjBAOe2ljeRtfOgyQxDlf2WSBCOjQu9as7R4ulYa7166561ACsshNiawVIghb9zv5kmuvveTk/VpDIKucVTVoh4gQwjAMAck21qhUYM3ZIKW0z1YQwjIBrbCvlWogcYSQdzvsrGvufvjJJx++66ozD9udQ0AxalBKpQKWAdjlpLsXfbutvxTFlvq3fbv4npN3AZDhIKWUUjNFwubjHv2kKxLs+vSxY5tDkZnq/5OKZtB2zsLOSLxj0bltYFacFKPnsgHSyct6Iqs9S08kNOCcjlGTi+XBHk90RtY7ntgDyitOVvF6NpcDJ34wGjk4+sGJWA7P0mOoqoDHQLpyQ+ToxqsZx+Agrcr0MA6b7+yKnO26uxnj0FPlJn2O4fv6Iof77m2OYT9ZlkrnmYjwpt7I6Z6bkIg4n1aGNQUiOGtb5HjHOUBUmKaMPcADvo6c//pABE+Z6wy/Fo3D15szWkDpYN14WDdPK9Htruhxr/eyCUq44qQtrm09qULJ7/G1W1/urqzmXhxyZ+jFnLKcPuMnV346I63s+w90utD5QE45mWx+YZutjuc5qVydMO++n0bkSj/cu0OFcllPP+rlXwYkBn595ejtlfsV0/e8dv5Xm/tKcaW+zV/Ov2bP6RXKIlZQOCAWAgAA0AwAnQEqSwBLAD6BNJRHpSMiITmYCACgEAllAFbF+A25LE5yII8A5+jPLzK1JLF2ujFXPgdP5oKoql25pUJoJ4iujWHGyjgIegNkSZGJ+zQ6v9bw5wf9ighavfOKj88N/aGXCIow3NDVOlGb+jMAAP7yGX/+Wh//yw///5WIiiyqFbn0+Hm4XxC7su/R1RfYGUI/S+8a5YmTN7wMdTgCh83HCiIk3l/2EAxWb0CpHuzFnnyNENXYoMPyX4DPRItqMneRFqz+GBQShmuugnmEG6r7+gLVhar0rzrqbXDtnsjJ/BjRgu2W21XmJzwMfIll/flF5DVe/V9QQaV/cXkDqJmBKXi+gJqmx5BB9mbb3AxZtOIjmcHq+eZmp5tgT2klQiMwo6AfkJy8n0RePLdDQh6Nae9PXnOI1Q4kdlAyczedZb1BXF5UdIT8SG5/FxJ6QiXvIn/+87ugiKlQfwzeE6de0giJxpZLf1XHpIGyA2iW3lnJE1JZwXAuSU/D/CVE0u7rG3wlLobV1tipTWR7qwqQLF6dcbjiwocLndt3XKBG+a7u6sjFTwvkDJwvk/sV1wdmW8D4Vzi9Oj//hNq9w/LrOJW2GORcrj83/kLCf3yljsns0y0zTvYkGPLzTbYW9ah+Wo3/mOipxl4n48K9UsY8jN3UrHcaQ2tHTDIVKe/1xz56lrDllbS133BZ+8rZYtcgAAAA
  DEFAULT_BIO: 这个人很神秘，什么也没有写  # 默认用户bio

Limits:
  AVATAR_SIZE_RANGE:           # 头像大小限制 默认[0, 1024] 单位: KB
    MIN: 0
    MAX: 1024
  REASON_LENGTH_RANGE:         # 申请理由/入群问题回答长度限制 默认[0, 32]
    MIN: 0
    MAX: 32
  USER_NAME_LENGTH_RANGE:      # 用户昵称长度限制 默认[1, 16]
    MIN: 1
    MAX: 16
  USER_BIO_LENGTH_RANGE:       # 用户Bio长度限制 默认[0, 32]
    MIN: 0
    MAX: 32
  GROUP_NAME_LENGTH_RANGE:     # 群名长度限制 默认[1, 16]
    MIN: 1
    MAX: 16
  GROUP_QA_LENGTH_RANGE:       # 入群问题长度限制 默认[0, 32]
    MIN: 0
    MAX: 32
  GROUP_ANN_LENGTH_RANGE:      # 群公告长度限制 默认[0, 512]
    MIN: 0
    MAX: 512
  GROUP_AUDIO_LENGTH_RANGE:    # 语音消息长度限制 默认[1, 50] 单位: 秒
    MIN: 1
    MAX: 50
  GROUP_FILE_SIZE_RANGE:       # 群文件大小限制 默认[0, 512000] 单位: KB
    MIN: 0
    MAX: 512000
  GROUP_TEXT_LENGTH_RANGE:     # 发送文本信息的最大长度 默认[0, 4096]
    MIN: 0
    MAX: 4096
  GROUP_IMAGE_SIZE_RANGE:      # 发送图片信息的最大大小 默认[0, 2048] 单位: KB  (前端会转换为webp再发送，4K图片也只有100多KB)
    MIN: 0
    MAX: 2048
  GROUP_BAN_MAX_TIME: 43200           # 群禁言最大时长 默认43200 单位：分钟
  MESSAGE_EXPIRE_MINUTES: 10080       # 群消息过期时间(超过此时间还未接收就不会再收到) 默认10080 单位：分钟
  REQUEST_EXPIRE_MINUTES: 10080       # 申请过期时间(入群申请，好友申请) 默认10080 单位：分钟
  NOTIFICATION_EXPIRE_MINUTES: 10080  # 通知过期时间(如被移除管理员的通知) 默认10080 单位：分钟
  MAX_DEVICE: 16                      # 最大设备数 默认16 (默认最多只能在16台设备上登录，超过优先淘汰最久未登录的设备，如果被淘汰，那么用这台设备再次登录不会再接收到未登录期间的消息)
  MAX_ONLINE_DEVICE: 4                # 最大同时在线设备数 默认4
  MESSAGE_RATE: 20                    # 同一个用户在1s内最多发送多少条消息，不限制填入-1