Database:
  HOST: localhost
  PORT: 27017
  MAX_POOL_SIZE: 50

Auth:
  SECRET_KEY: hw4jf6uz8o4na1rc3pf9yxr8fn3gft3m  # JWT密钥
  SALT: jSJ1oGX6siEa50Nmq6xlYvD0IfnUlKrj        # 密码加盐
  USER_ACCESS_TOKEN_EXPIRE_MINUTES: 2160        # 用户Token过期时间 默认2160 单位: 分钟
  BOT_ACCESS_TOKEN_EXPIRE_MINUTES: 525600       # 机器人Token过期时间 默认525600 单位: 分钟

Default:
  # 用户/群的默认头像 base64格式
  DEFAULT_AVATAR: data:image/png;base64,/9j/4AAQSkZJRgABAQEAkACQAAD/2wBDAAIBAQIBAQICAgICAgICAwUDAwMDAwYEBAMFBwYHBwcGBwcICQsJCAgKCAcHCg0KCgsMDAwMBwkODw0MDgsMDAz/2wBDAQICAgMDAwYDAwYMCAcIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/wAARCAAwADADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDzeiiiugzCiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooA//2Q==
  DEFAULT_BIO: 这个人很神秘，什么也没有写  # 默认用户bio

Limits:
  AVATAR_SIZE_RANGE:           # 头像大小限制 默认[0, 1024] 单位: KB
    MIN: 0
    MAX: 1024
  REASON_LENGTH_RANGE:         # 申请理由/入群问题回答长度限制 默认[0, 64]
    MIN: 0
    MAX: 64
  USER_NAME_LENGTH_RANGE:      # 用户昵称长度限制 默认[1, 16]
    MIN: 1
    MAX: 16
  USER_PASSWORD_LENGTH_RANGE:  # 用户密码长度限制 默认[6, 16]
    MIN: 6
    MAX: 16
  GROUP_NAME_LENGTH_RANGE:     # 群名长度限制 默认[1, 16]
    MIN: 1
    MAX: 16
  GROUP_QA_LENGTH_RANGE:       # 入群问题长度限制 默认[0, 32]
    MIN: 0
    MAX: 32
  GROUP_AUDIO_LENGTH_RANGE:    # 语音消息长度限制 默认[1, 50] 单位: 秒
    MIN: 1
    MAX: 50
  GROUP_FILE_SIZE_RANGE:       # 群文件大小限制 默认[0, 102400] 单位: KB
    MIN: 0
    MAX: 102400
  REQUEST_EXPIRE_MINUTES: 10080    # 申请过期时间 默认10080 单位：分钟
  MAX_DEVICE: 6                    # 最大设备数 默认6 (默认最多只能在6台设备上登录，超过优先淘汰最久未登录的设备，如果被淘汰，那么这台设备不会再接收到未登录期间的消息)
  MAX_ONLINE_DEVICE: 2             # 最大同时在线设备数 默认2