Database:
  HOST: localhost
  PORT: 27017
  MAX_POOL_SIZE: 100

Auth:
  SECRET_KEY: hw4jf6uz8o4na1rc3pf9yxr8fn3gft3m  # JWT密钥
  SALT: jSJ1oGX6siEa50Nmq6xlYvD0IfnUlKrj        # 密码加盐
  USER_ACCESS_TOKEN_EXPIRE_MINUTES: 2160        # 用户Token过期时间 默认2160 单位: 分钟
  BOT_ACCESS_TOKEN_EXPIRE_MINUTES: 2628000      # 机器人Token过期时间 默认2628000 单位: 分钟

Default:
  # 用户/群的默认头像 base64格式
  DEFAULT_AVATAR: data:image/png;base64,/9j/4AAQSkZJRgABAQEAkACQAAD/2wBDAAIBAQIBAQICAgICAgICAwUDAwMDAwYEBAMFBwYHBwcGBwcICQsJCAgKCAcHCg0KCgsMDAwMBwkODw0MDgsMDAz/2wBDAQICAgMDAwYDAwYMCAcIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/wAARCAAwADADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDzeiiiugzCiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooA//2Q==
  DEFAULT_BIO: 这个人很神秘，什么也没有写  # 默认用户bio

Limits:
  AVATAR_SIZE_RANGE:           # 头像大小限制 默认[0, 1024] 单位: KB
    MIN: 0
    MAX: 1024
  REASON_LENGTH_RANGE:         # 申请理由/入群问题回答长度限制 默认[0, 32]
    MIN: 0
    MAX: 32
  USER_NAME_LENGTH_RANGE:      # 用户昵称长度限制 默认[1, 16]
    MIN: 1
    MAX: 16
  USER_BIO_LENGTH_RANGE:       # 用户Bio长度限制 默认[0, 32]
    MIN: 0
    MAX: 32
  GROUP_NAME_LENGTH_RANGE:     # 群名长度限制 默认[1, 16]
    MIN: 1
    MAX: 16
  GROUP_QA_LENGTH_RANGE:       # 入群问题长度限制 默认[0, 32]
    MIN: 0
    MAX: 32
  GROUP_ANN_LENGTH_RANGE:      # 群公告长度限制 默认[0, 512]
    MIN: 0
    MAX: 512
  GROUP_AUDIO_LENGTH_RANGE:    # 语音消息长度限制 默认[1, 50] 单位: 秒
    MIN: 1
    MAX: 50
  GROUP_FILE_SIZE_RANGE:       # 群文件大小限制 默认[0, 512000] 单位: KB
    MIN: 0
    MAX: 512000
  GROUP_TEXT_LENGTH_RANGE:     # 发送文本信息的最大长度 默认[0, 1024]
    MIN: 0
    MAX: 1024
  GROUP_IMAGE_SIZE_RANGE:      # 发送图片信息的最大大小 默认[0, 1024] 单位: KB  (前端会转换为webp再发送，4K图片也只有100多KB)
    MIN: 0
    MAX: 1024
  MESSAGE_EXPIRE_MINUTES: 10080       # 群消息过期时间(超过此时间还未接收就不会再收到) 默认10080 单位：分钟
  REQUEST_EXPIRE_MINUTES: 10080       # 申请过期时间(入群申请，好友申请) 默认10080 单位：分钟
  NOTIFICATION_EXPIRE_MINUTES: 10080  # 通知过期时间(如被移除管理员的通知) 默认10080 单位: 分钟
  MAX_DEVICE: 6                       # 最大设备数 默认6 (默认最多只能在6台设备上登录，超过优先淘汰最久未登录的设备，如果被淘汰，那么用这台设备再次登录不会再接收到未登录期间的消息)
  MAX_ONLINE_DEVICE: 3                # 最大同时在线设备数 默认3
  MESSAGE_RATE: 20                    # 同一个用户在1s内最多发送多少条消息，不限制填入-1